### ISSUE TITLE
Slow typing

### ISSUE THREAD

**Issue by msdi** [simasch/gted#12]
Hi,

we tested the plugin with a small po file, but when we decided to use it for real with a file containing 22k lines, typing is terribly slow... About 3-4 seconds between the typed key and the display of the key on the screen. Copy pasting is fast and general use is fast. Even sorting the 22k msgid in the list is really fast.

If we go in header or source, it's really fast also.

Not sure if there is something you run on key press, if so maybe it could get improved.

Regards

**Comment by simasch** [comment]
I'm sorry but I cannot reproduce this issue with Zend Studio.

Do you have issues with other tools as well?
