### ISSUE TITLE
CreateProcess error=206 The filename or extension is too long

### ISSUE THREAD

**Issue by adamsrl** [simasch/gted#14]
Hi,
I can't update my PO files, I got this error:
Cannot run program "xgettext" (in directory "P:\adamweb"): CreateProcess error=206, The filename or extension is too long
As you can see the paths are as short as possible, any idea?
Eclipse version: Juno (4.2.1) and Kepler [same error on both]
gted version: 1.5.5
gettext version: 0.18.3

Thanks
Davide

**Comment by nkovalenko93** [comment]
How did you use it? Can you describe?
